### ISSUE TITLE
project report

### ISSUE THREAD

**Issue by Muhandisbro** [Alexis-Georganopoulos/Bipedal_Robot_PID#1]
Hi, thanks for making this amazing bipedal walker, im wondering if you can share this project report or any relevant resources, thanks and regard

**Comment by alexios1994** [comment]
Hello @Muhandisbro , there aren't any project reports or relevant resources, beyond hand drawn sketches. This project was made as-is. What you see is about 99% of what exists.

**Comment by Alexis-Georganopoulos** [comment]
Hello @Muhandisbro , there aren't any project reports or main resources, beyond hand drawn sketches. This project was made as-is. What you see is about 99% of what exists.
The wikipedia article on impedance control (and it's references), (inverse)kinematic theory, and passive walkers is roughly the other 1%

**Comment by Muhandisbro** [comment]
thank you for your response, I appreciate it

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
